// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelJob(arg1) {
  return window['go']['wailsapi']['Backend']['CancelJob'](arg1);
}

export function DeleteMachine(arg1) {
  return window['go']['wailsapi']['Backend']['DeleteMachine'](arg1);
}

export function Execute(arg1, arg2, arg3, arg4) {
  return window['go']['wailsapi']['Backend']['Execute'](arg1, arg2, arg3, arg4);
}

export function ExecuteStream(arg1, arg2, arg3, arg4) {
  return window['go']['wailsapi']['Backend']['ExecuteStream'](arg1, arg2, arg3, arg4);
}

export function ExecuteStreamEvents(arg1, arg2, arg3, arg4) {
  return window['go']['wailsapi']['Backend']['ExecuteStreamEvents'](arg1, arg2, arg3, arg4);
}

export function ExportMachines(arg1, arg2) {
  return window['go']['wailsapi']['Backend']['ExportMachines'](arg1, arg2);
}

export function ImportMachines(arg1, arg2) {
  return window['go']['wailsapi']['Backend']['ImportMachines'](arg1, arg2);
}

export function ListMachines() {
  return window['go']['wailsapi']['Backend']['ListMachines']();
}

export function RecentHistory(arg1) {
  return window['go']['wailsapi']['Backend']['RecentHistory'](arg1);
}

export function RecentHistoryFiltered(arg1, arg2, arg3) {
  return window['go']['wailsapi']['Backend']['RecentHistoryFiltered'](arg1, arg2, arg3);
}

export function SetCtx(arg1) {
  return window['go']['wailsapi']['Backend']['SetCtx'](arg1);
}

export function Shutdown(arg1) {
  return window['go']['wailsapi']['Backend']['Shutdown'](arg1);
}

export function StartJob(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['wailsapi']['Backend']['StartJob'](arg1, arg2, arg3, arg4, arg5);
}

export function UpsertMachine(arg1) {
  return window['go']['wailsapi']['Backend']['UpsertMachine'](arg1);
}
