// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelJob(arg1) {
  return window['go']['wailsapi']['Backend']['CancelJob'](arg1);
}

export function DeleteMachine(arg1) {
  return window['go']['wailsapi']['Backend']['DeleteMachine'](arg1);
}

export function Execute(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['wailsapi']['Backend']['Execute'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function ExecuteStream(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['wailsapi']['Backend']['ExecuteStream'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function ExecuteStreamChunks(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['wailsapi']['Backend']['ExecuteStreamChunks'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function ExecuteStreamEvents(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['wailsapi']['Backend']['ExecuteStreamEvents'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function ExportMachines(arg1, arg2) {
  return window['go']['wailsapi']['Backend']['ExportMachines'](arg1, arg2);
}

export function GetGlobalSSHKey() {
  return window['go']['wailsapi']['Backend']['GetGlobalSSHKey']();
}

export function HasGlobalSSHKey() {
  return window['go']['wailsapi']['Backend']['HasGlobalSSHKey']();
}

export function ImportMachines(arg1, arg2) {
  return window['go']['wailsapi']['Backend']['ImportMachines'](arg1, arg2);
}

export function ListMachines() {
  return window['go']['wailsapi']['Backend']['ListMachines']();
}

export function MachinesLookup(arg1) {
  return window['go']['wailsapi']['Backend']['MachinesLookup'](arg1);
}

export function RecentHistory(arg1) {
  return window['go']['wailsapi']['Backend']['RecentHistory'](arg1);
}

export function RecentHistoryFiltered(arg1, arg2, arg3) {
  return window['go']['wailsapi']['Backend']['RecentHistoryFiltered'](arg1, arg2, arg3);
}

export function SetCtx(arg1) {
  return window['go']['wailsapi']['Backend']['SetCtx'](arg1);
}

export function SetGlobalSSHKey(arg1) {
  return window['go']['wailsapi']['Backend']['SetGlobalSSHKey'](arg1);
}

export function Shutdown(arg1) {
  return window['go']['wailsapi']['Backend']['Shutdown'](arg1);
}

export function StartJob(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['wailsapi']['Backend']['StartJob'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function UpsertMachine(arg1) {
  return window['go']['wailsapi']['Backend']['UpsertMachine'](arg1);
}
