// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';
import {context} from '../models';

export function CancelJob(arg1:string):Promise<boolean>;

export function DeleteMachine(arg1:string):Promise<void>;

export function Execute(arg1:string,arg2:Array<number>,arg3:number,arg4:number,arg5:string,arg6:string):Promise<Array<domain.ExecResult>>;

export function ExecuteStream(arg1:string,arg2:Array<number>,arg3:number,arg4:number,arg5:string,arg6:string):Promise<Array<domain.ExecResult>>;

export function ExecuteStreamChunks(arg1:string,arg2:Array<number>,arg3:number,arg4:number,arg5:string,arg6:string):Promise<void>;

export function ExecuteStreamEvents(arg1:string,arg2:Array<number>,arg3:number,arg4:number,arg5:string,arg6:string,arg7:boolean):Promise<void>;

export function ExportMachines(arg1:string,arg2:boolean):Promise<string>;

export function GetGlobalSSHKey():Promise<string>;

export function HasGlobalSSHKey():Promise<boolean>;

export function ImportMachines(arg1:string,arg2:string):Promise<number>;

export function ListMachines():Promise<Array<domain.Machine>>;

export function MachinesLookup(arg1:Array<string>):Promise<Array<domain.Machine>>;

export function RecentHistory(arg1:number):Promise<Array<domain.ExecHistory>>;

export function RecentHistoryFiltered(arg1:number,arg2:string,arg3:string):Promise<Array<domain.ExecHistory>>;

export function SetCtx(arg1:context.Context):Promise<void>;

export function SetGlobalSSHKey(arg1:string):Promise<void>;

export function Shutdown(arg1:context.Context):Promise<void>;

export function StartJob(arg1:string,arg2:string,arg3:Array<number>,arg4:number,arg5:number,arg6:string,arg7:string,arg8:boolean):Promise<string>;

export function UpsertMachine(arg1:domain.Machine):Promise<void>;
